### ISSUE TITLE
Failed to initialize Redis in scheduler when django-redis-cache package is used

### ISSUE THREAD

**Issue by atten** [rq/django-rq#443]
**Requirements:**
django-rq == 1.5.1
django-redis-cache == 2.1.1

Since 1.5.0, Redis instances are initialized from connection kwargs instead of re-using existing connection (https://github.com/rq/rq/blob/a09a2ab3b49e20c95e76d37a8b496235e69fcfd8/rq/scheduler.py#L60).

When I use **django-redis-cache**, `USE_REDIS_CACHE` option and run rq-scheduler (`--with-scheduler` option), it leads to following error:

```
  File "/home/user/trade-bot-001/botmanager/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/user/.cache/pypoetry/virtualenvs/botmanager-god_kShI-py3.7/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/user/.cache/pypoetry/virtualenvs/botmanager-god_kShI-py3.7/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/user/.cache/pypoetry/virtualenvs/botmanager-god_kShI-py3.7/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/user/.cache/pypoetry/virtualenvs/botmanager-god_kShI-py3.7/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/home/user/.cache/pypoetry/virtualenvs/botmanager-god_kShI-py3.7/lib/python3.7/site-packages/django_rq/management/commands/rqworker.py", line 102, in handle
    w.work(burst=options.get('burst', False), with_scheduler=options.get('with_scheduler', False), logging_level=level)
  File "/home/user/.cache/pypoetry/virtualenvs/botmanager-god_kShI-py3.7/lib/python3.7/site-packages/rq/worker.py", line 516, in work
    self.scheduler.acquire_locks()
  File "/home/user/.cache/pypoetry/virtualenvs/botmanager-god_kShI-py3.7/lib/python3.7/site-packages/rq/scheduler.py", line 87, in acquire_locks
    if self.connection.set(self.get_locking_key(name), pid, nx=True, ex=5):
  File "/home/user/.cache/pypoetry/virtualenvs/botmanager-god_kShI-py3.7/lib/python3.7/site-packages/rq/scheduler.py", line 61, in connection
    self._connection = Redis(**self._connection_kwargs)
TypeError: __init__() got an unexpected keyword argument 'parser_class'
```

Redis(...) constructor is called with **self._connection_kwargs:

```
{'db': 1, 'password': None, 'parser_class': <class 'redis.connection.PythonParser'>, 'socket_timeout': None, 'socket_connect_timeout': None, 'host': 'localhost', 'port': 6389}
```

It's needed to handle (or omit) keyword argument 'parser_class' which is valid for `redis.Connection(...)`, but not for `Redis(...)` itself.

**Comment by selwin** [comment]
This should be fixed in https://github.com/rq/rq/pull/1327 . Will do a release soon.

**Comment by atten** [comment]
Thanks, but it didn't help:

```
./manage.py rqworker main --with-scheduler
Exception ignored in: <function Redis.__del__ at 0x7f43a628c4d0>
Traceback (most recent call last):
  File "/home/user/.cache/pypoetry/virtualenvs/botmanager-god_kShI-py3.7/lib/python3.7/site-packages/redis/client.py", line 885, in __del__
    self.close()
  File "/home/user/.cache/pypoetry/virtualenvs/botmanager-god_kShI-py3.7/lib/python3.7/site-packages/redis/client.py", line 888, in close
    conn = self.connection
AttributeError: 'Redis' object has no attribute 'connection'
Traceback (most recent call last):
  File "/home/user/trade-bot-001/botmanager/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/user/.cache/pypoetry/virtualenvs/botmanager-god_kShI-py3.7/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/user/.cache/pypoetry/virtualenvs/botmanager-god_kShI-py3.7/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/user/.cache/pypoetry/virtualenvs/botmanager-god_kShI-py3.7/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/user/.cache/pypoetry/virtualenvs/botmanager-god_kShI-py3.7/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/home/user/.cache/pypoetry/virtualenvs/botmanager-god_kShI-py3.7/lib/python3.7/site-packages/django_rq/management/commands/rqworker.py", line 102, in handle
    w.work(burst=options.get('burst', False), with_scheduler=options.get('with_scheduler', False), logging_level=level)
  File "/home/user/.cache/pypoetry/virtualenvs/botmanager-god_kShI-py3.7/lib/python3.7/site-packages/rq/worker.py", line 516, in work
    self.scheduler.acquire_locks()
  File "/home/user/.cache/pypoetry/virtualenvs/botmanager-god_kShI-py3.7/lib/python3.7/site-packages/rq/scheduler.py", line 89, in acquire_locks
    if self.connection.set(self.get_locking_key(name), pid, nx=True, ex=5):
  File "/home/user/.cache/pypoetry/virtualenvs/botmanager-god_kShI-py3.7/lib/python3.7/site-packages/rq/scheduler.py", line 63, in connection
    self._connection = self._connection_class(**self._connection_kwargs)
TypeError: __init__() got an unexpected keyword argument 'parser_class'
15:01:13 Worker rq:worker:a6364e698055489fb9163efc38b48e99: started, version 1.5.2
15:01:13 *** Listening on PRIORITY, workers_combined, workers_reports, workers_batched...
15:01:13: Trying to acquire locks for main

Process finished with exit code 1
```

django-rq == 2.3.2
rq == 1.5.2
django-redis-cache == 2.1.1

**Comment by atten** [comment]
@selwin Why don't you re-open this issue? It's not yet fixed

**Comment by selwin** [comment]
Because it's an issue with RQ itself, not django-rq :)
