### ISSUE TITLE
Error in job_detail.html at line 226

### ISSUE THREAD

**Issue by bibenga** [rq/django-rq#634]
Hello,

I think that an error present in template job_detail.html at line 226.
I guess that line should be without {{ result.Type }} or with {{ result.type }}.
The django template rendering failed with error:

![error](https://github.com/rq/django-rq/assets/13942981/3081a9aa-1fc6-4389-a6f1-f8384074c867)

Thanks.

**Comment by selwin** [comment]
Fixed in https://github.com/rq/django-rq/pull/639

**Comment by applecat** [comment]
Is it possible to release a new version with this fix? I have installed 2.10.1 and this error still in it. 
PS. Thank you for Django RQ!
